# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea6b5580ad35d6272768f62df74296667e8a6303e2a13bb4086fdf42f0db1fc284af6f9a7c231a240164d4045516d7daf570d0558c0d76fe66f3402b6f250cb5

test:
  secret_key_base: 17507b05643734d5ceb581c656c74820330120aca04138d99fa3b519b36e96c973d4e39d92f49760abff880c26b27aaf4cc472a6ac777b00e599f199d1b93fba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
